services:
  audit-sink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audit-sink-service
    restart: unless-stopped
    environment:
      SERVER_PORT: "${SERVER_PORT:-8081}"
      SPRING_DATASOURCE_URL: "${POSTGRES_URL:-jdbc:postgresql://helios:5432/auditdb}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER:-postgres}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      SPRING_FLYWAY_ENABLED: "${FLYWAY_ENABLED:-false}"
      AUDIT_AUTH_APIKEY: "${AUDIT_API_KEY:-dev-key}"
      JAVA_OPTS: "-XX:MaxRAMPercentage=75 -Djava.security.egd=file:/dev/./urandom"
    ports:
      - "${SERVER_PORT:-8081}:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "X-Api-Key: ${AUDIT_API_KEY:-dev-key}", "http://localhost:8081/audit/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
