
server:
  port: 8081

spring:
  application:
    name: audit-sink
  datasource:
    url: jdbc:postgresql://helios:5432/auditdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: false
    schemas: public
    baseline-on-migrate: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

audit:
  auth:
    # set a random string here in prod and require clients to send X-Api-Key
    apiKey: dev-key
  redaction:
    # keys that should be masked recursively if present in argsRedacted/resultRedacted maps
    redactKeys: [ "password", "token", "secret", "attachment", "content", "data" ]
  payload:
    maxJsonBytes: 4096
